<?php

/**
 * @file
 * Islandora DTU talk solution pack module
 */
define('ISLANDORA_DTU_MXD_TALK_FORM_NAME', 'DTU MXD-DDF Talk Form');
define("FEDORA_REPOSITORY_PATH",'/fedora/repository');
define('FLEXPAPER_VIEWER_PATH','sites/all/libraries/flexpaper/FlexPaperViewer.swf');

/**
 * islandora dtu talk required fedora objects
 * @return type 
 */
function islandora_dtu_mxd_talk_required_fedora_objects() {


  $module_path = drupal_get_path('module', 'islandora_dtu_mxd_talk');

  // Put the form in the database
  module_load_include('inc', 'xml_form_builder', 'XMLFormDatabase');
  if (!XMLFormDatabase::Exists(ISLANDORA_DTU_MXD_TALK_FORM_NAME)) {
    $definition = new DOMDocument();
    $definition->load($module_path . '/xml/mxd_talk_form.xml');
    XMLFormDatabase::Create(ISLANDORA_DTU_MXD_TALK_FORM_NAME, $definition);
  }

  // Associates the form with the content model
  $result = db_result(db_query('Select content_model from {islandora_content_model_forms} where  content_model = "%s" and form_name = "%s"', 'islandora:dtu_mxd_talk_cmodel', 'DTU MXD-DDF Talk Form'));
  if (!$result) {
    $object = new stdClass();
    $object->content_model = 'islandora:dtu_mxd_talk_cmodel';
    $object->form_name = 'DTU MXD-DDF Talk Form';
    $object->dsid = 'MXD';
    $object->title_field = "['title']['original']['main']";
    $object->transform = 'mxd_to_dc.xsl';
    $result = drupal_write_record('islandora_content_model_forms', $object);
  }

  return array(
    'islandora_dtu_mxd_talk' => array(
      'module' => 'islandora_dtu_mxd_talk',
      'title' => 'DTU MXD Talk Content Models',
      'objects' => array(
        array(
          'pid' => 'islandora:dtu_mxd_talk_cmodel',
          'label' => 'DTU MXD Conference Talk content model',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/DTU_MXD_TALKCM.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'islandora:dtu_dc_video_cmodel',
          'label' => 'Add Video to collection',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/DTU_DC_VIDEOCM.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'islandora:dtu_dc_slide_cmodel',
          'label' => 'Add Video to collection',
          'dsid' => 'ISLANDORACM',
          'datastream_file' => "$module_path/xml/DTU_DC_SLIDECM.xml",
          'cmodel' => 'fedora-system:ContentModel-3.0',
        ),
        array(
          'pid' => 'islandora:dtu_talk_collection',
          'label' => 'DTU Talk Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => variable_get('fedora_repository_pid', 'islandora:root'),
          'datastreams' => array(
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/COLLECTION_POLICY.xml",
            ),
          ),
        ),
      ),
    ),
  );
}

/**
 * Implementation of hook_menu
 * Providing custom callbacks for custom full-window iframe colorbox popups
 */
function islandora_dtu_mxd_talk_menu() {
  $items = array();
  $items['islandora/dtu/renderpdf/%'] = array(
    'title' => 'Special Page',
    'page callback' => 'islandora_dtu_mxd_talk_pdfiframe',
    'page arguments' => array(3),
    'access arguments' => array('view fedora collection'),
    'type' => MENU_CALLBACK,
  );
  $items['islandora/dtu/renderpdf/%/%'] = array(
    'title' => 'Special Page',
    'page callback' => 'islandora_dtu_mxd_talk_pdfiframe',
    'page arguments' => array(3,4),
    'access arguments' => array('view fedora collection'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * return output for PDF/SWF render page
 * 
 * @return text
 */
function islandora_dtu_mxd_talk_pdfiframe($pid,$option = null) {
  if ($pid == 'FlexPaperViewer.swf' || $option == 'FlexPaperViewer.swf' ) {
    drupal_goto(FLEXPAPER_VIEWER_PATH);
  }
  
  global $base_url;
  
  if( empty( $pid )) {
    return "No PID specified";
  }
  
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $item = new Fedora_Item($pid);
  if( empty( $item )) {
    return "Invalid PID: $pid";
  }
  
  $pdfds = (isset($item->datastreams['OBJ']) ? 'OBJ' : null );
  $swfds = (isset($item->datastreams['OBJSWF']) ? 'OBJSWF' : null );
  if( empty( $pdfds ) && strcasecmp( $option,'forceswf' )) {
    return "No PDF object for $pid";
  }
  
  $label = preg_replace('/%u(\d+)/','&#x$1;',$item->objectProfile->objLabel);
  $filename = $label . ".pdf";
  
  $pdf_url = (isset($pdfds) ? $base_url . FEDORA_REPOSITORY_PATH . "/" . $pid . "/" . $pdfds . "/Paper.pdf" : null );
  $swf_url = (isset($swfds) ? $base_url . FEDORA_REPOSITORY_PATH . "/" . $pid . "/" . $swfds . "/Paper.swf" : null );
  $nice_pdf_url = (isset($pdfds) ? $base_url . FEDORA_REPOSITORY_PATH . "/" . $pid . "/" . $pdfds . "/" . $filename : null);
  unset($item);
  
  $_SESSION['dtu-paper-pdf-url'] = (strcmp($option,'forceswf') ? $pdf_url : null );
  $_SESSION['dtu-paper-swf-url'] = (strcmp($option,'forcepdf') ? $swf_url : null );

  if (!strcasecmp($option,'forceswf')) {
    return theme('islandora_dtu_mxd_talk_pdfiframe', "Your browser doesn't appear to be able to handle javascript and SWF files; here is a direct link to the PDF file: <a href=\"$swf_url\">$pid</a>");
  } else {
    return theme('islandora_dtu_mxd_talk_pdfiframe', "Your browser doesn't appear to be able to handle PDF or SWF files; here is a direct link to the PDF file: <a href=\"$nice_pdf_url\">$pid</a>");
  }
  
}

function islandora_dtu_mxd_talk_theme() {
  return array(
    'islandora_dtu_mxd_talk_pdfiframe' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

function theme_islandora_dtu_mxd_talk_pdfiframe($text) {
  return $text;
}

/**
 * Implementation of hook_define_layouts
 * providing custom functionality for taxonomy rockstar
 *
 * @return array of layout options key => text
 */
function islandora_dtu_mxd_talk_fedora_ingest_related_object() {
  return array(
    'islandora_dtu_mxd_talk' => array(
      'module' => 'islandora_dtu_mxd_talk',
      'file' => 'dtu_mxd_talk.inc',
      'class' => 'TalkObjectHelper',
      'method' => 'ingest_secondary_fedora_objects',
    ),
  );
}

/**
 * 
 * 
 */
function islandora_dtu_mxd_talk_theme_registry_alter(&$theme_registry) {
  $theme_hook = 'page';
  // Get the path to this module
  $modulepath = drupal_get_path('module', 'islandora_dtu_mxd_talk');
  // Add the module path on top in the array of paths
  array_unshift($theme_registry[$theme_hook]['theme paths'], $modulepath);
}

